### ISSUE TITLE
Do a mock-up on people recommendation

### ISSUE THREAD

**Issue by iryna1** [CyberCRI/learn-ext#133]

**Comment by xuanqi1122** [comment]
context: The new user (example: new person arriving at CRI) wants to meet people within a specific subgroup/community. He indicates (in CRI people?) keywords that describe him best based on: SDGs of interest concepts s.he masters concepts s.he wants to learn about Clicks ok. Then can log out or waits for others of the community to finish. Then s.he (logs in and) chooses groups of people she wants to be matched to (all CRI, their study program...), and clicks on "match me!" The algorithm calculates common concepts/categories/portals and outputs the names of one or several other users and indicates common points/ complementarities.

**Comment by iryna1** [comment]
Info sketched here:
https://docs.google.com/document/d/1aRMgE1Hz7od667UtkRvyYB8ABGGylKgJLPynI24_u6c/edit?usp=sharing
