### ISSUE TITLE
iLearn pop-up not disappearing after a few seconds

### ISSUE THREAD

**Issue by jmsevin** [CyberCRI/learn-ext#4]

**Comment by xuanqi1122** [comment]
@jmsevin Can you explain more about this issue? Do you mean that it doesn't autonomically disappear if the user does not choose a difficulty level? 

I think this issue will be resolved when we add a confirmation button. If you agree with this, could we close this issue to avoid confusion?

**Comment by prashnts** [comment]
It's no longer relevant, but it was! So long. 📦
