### ISSUE TITLE
Text not displaying correctly on the map

### ISSUE THREAD

**Issue by lioneldeveauxcri** [CyberCRI/learn-ext#44]
See attached.
I am on Chrome, the latest version.
Windows 10.
Screen resolution 1920x1080, text height 150%.
<img width="940" alt="Annotation 2019-12-11 142944" src="https://user-images.githubusercontent.com/55746438/70625477-b9ce6b00-1c22-11ea-8a4d-84298627f84a.png">

**Comment by prashnts** [comment]
Thanks @lioneldeveauxcri I fixed it in latest version. Please reopen this in case it wasnt fixed!

**Comment by lioneldeveauxcri** [comment]
I checked: it's fixed :)
