### ISSUE TITLE
Chrome Store - text&image update

### ISSUE THREAD

**Issue by xuanqi1122** [CyberCRI/learn-ext#52]
Since the extension has been updated, we need to update its corresponding introduction/image/contact too.

See the screenshot and corresponding refinement:
<img width="946" alt="Capture d'écran 2019-12-18 15 39 56" src="https://user-images.githubusercontent.com/11083084/71095357-c156bc80-21ac-11ea-996e-177aa1b484b4.png">
iLearn => WeLearn
3 language => 4 (Add Simplified Chinese)
ilearn@cri-paris.org => welearn@cri-paris.org

For the demonstration:
It's better for us to find an another image to replace this one:
(All images has "iLearn" on the left top)
<img width="683" alt="Capture d'écran 2019-12-18 15 42 54" src="https://user-images.githubusercontent.com/11083084/71095553-1b578200-21ad-11ea-8f3f-a3a23e5201ca.png">

Let me know what I can help you to update all these : )

**Comment by xuanqi1122** [comment]
suggestions of replacement
<img width="1044" alt="Capture d’écran 2019-12-18 à 15 56 05" src="https://user-images.githubusercontent.com/11083084/71096604-e8ae8900-21ae-11ea-9b14-248f577ae448.png">
<img width="1020" alt="Capture d’écran 2019-12-18 à 15 56 26" src="https://user-images.githubusercontent.com/11083084/71096634-f49a4b00-21ae-11ea-873d-b8329ea1f498.png">

**Comment by xuanqi1122** [comment]
<img width="962" alt="Capture d’écran 2019-12-18 à 16 21 20" src="https://user-images.githubusercontent.com/11083084/71098707-6fb13080-21b2-11ea-9122-112121a462ff.png">

**Comment by prashnts** [comment]
Done! Closing.
