### ISSUE TITLE
Replace the old Help page

### ISSUE THREAD

**Issue by xuanqi1122** [CyberCRI/learn-ext#57]
current page: chrome-extension://aheppdfnfcfnojcaipdajboppllolgpo/pages/support.html

The old tutorial was made for iLearn,  a new one is in demand for WeLearn.

**Comment by xuanqi1122** [comment]
New text is done.

How to use WeLearn?

Step1: Installation

Go to our official website, welearn.cri-paris.org and you will explore welearn as a guest. To have an individual account, click WELEARN on the left top, it will redirect you to an introduction page where there are extension download options available. We support both Chrome and Firefox.
 
For users who use neither Chrome nor Firefox, if it’s not too much trouble, we suggest you to install either browser before adding the extension.
Step2: Registration
After installing WeLearn extension, please follow the instruction to register yourself and then log in with your personal email address (**)
Step 3: Add resources to WeLearn
Now you can start adding resources by clicking the WeLearn button, usually on the right top of your browser, along with other extension buttons. The resources could be articles, news, blog posts, etc., as long as you read or watch them actively. Click the “anchor”, then it’s automatically saved to WeLearn.
While adding resources, the system will automatically analyze the context and mark concepts. On this popover, you can add or delete concepts that are extracted from the resource.
You can rate your understanding level of the resource in order for us to know your level of knowledge regarding the concepts and resources (which contributes to a personalized recommendation system.) And it’s done.
You can access previously added resources by clicking on the tab “My Resources” Right clicking the WeLearn button also direct you to “My Resources”.
Remark: It works better with texts that have over 1000 words; it does not work in PDFs, images(Coming soon!)
Step 4. Search for resources on “My Resources”
Here you can search for resources through concepts or keywords or try any words that you remember for targets resources
You can also go back to the original resource by clicking the link at the bottom of each card.
Step 5. Check out your knowledge map
When you go to “DISCOVER”, you can see your knowledge map, which is a visualization of your knowledge span.
The map layer of “My resources” represents all the resources that you have added to WeLearn.
The map layer of “My group” represents all the resources that have been added to a specific group that you have joined.
The map layer of “everyone” represents all the resources that have ever been added to WeLearn.

**Comment by prashnts** [comment]
Done in 6ac0ecb
