### ISSUE TITLE
Language placement inaccurate

### ISSUE THREAD

**Issue by lioneldeveauxcri** [CyberCRI/learn-ext#61]
Japonais and Créole Réunionais are two languages. However, they are very far away from one another on my map (see attached)
<img width="560" alt="japonais vs créole" src="https://user-images.githubusercontent.com/55746438/73669240-6a973a80-46a7-11ea-8c32-27cebf46f8d9.png">

**Comment by xuanqi1122** [comment]
issue solved with updated version of map
