### ISSUE TITLE
[Map] Maps are in French for all language settings

### ISSUE THREAD

**Issue by xuanqi1122** [CyberCRI/learn-ext#63]
In settings, people can choose one of 4 different languages, however, the map is always under French. For people who don't speak French at all, it might cause difficulty of understanding.

![atlas-im](https://user-images.githubusercontent.com/11083084/74541401-d4360500-4f41-11ea-8202-0bfa5940cb1b.png)

**Comment by prashnts** [comment]
Done! in #75
