### ISSUE TITLE
[Map] no island to show "my resources"

### ISSUE THREAD

**Issue by xuanqi1122** [CyberCRI/learn-ext#87]
I added 39 resources to a new account. But the map still shows like the following picture.
It is not about the amount of added resources. Something doesn't appear properly.

<img width="929" alt="capture_d_____cran_2020-02-28____14 05 09" src="https://user-images.githubusercontent.com/11083084/75551486-9c948600-5a34-11ea-8757-bd039b511f7e.png">

**Comment by prashnts** [comment]
Fixed in 179145b
