### ISSUE TITLE
plugin: Disconnect from 1 account and connect to another one impossible

### ISSUE THREAD

**Issue by iryna1** [CyberCRI/learn-ext#88]
When I disconnect from 1 account from the plugin and want to connect to another one: when I type connect, I should be back to the learning planet login page and not connect automatically to the account I disconnected from

**Comment by xuanqi1122** [comment]
https://github.com/CyberCRI/learn-ext/issues/86

I met the same situation and realised that we are using two system: website and extension, so the user needs to log out in both, in the FAQ page(https://welearn.cri-paris.org/pages/support.html#how-can-i-disconnect-or-switch-a-welearn-account) I explained as following:

How can I disconnect or switch a WeLearn account?
For both Chrome and Firefox user, firstly, go to Settings, Account - Log Out, and then:

For Chrome, right click on WeLearn Extension Button, Options - Disconnect.
For Firefox, right click on WeLearn Extension Button, Extension Preferences - Disconnect. Now you have disconnected. Repeat the login process to switch an account.

**Comment by iryna1** [comment]
ok, so we need tpo merge them so that it is transparent to the user.

**Comment by xuanqi1122** [comment]
already posted : )

**Comment by iryna1** [comment]
perfect
