### ISSUE TITLE
connecting to my account from an other computer: 0 resources

### ISSUE THREAD

**Issue by iryna1** [CyberCRI/learn-ext#90]
I connected on Xuanqi's computer to my account. I had 0 resources. Xuanqi added a new one. And then she had all the other resources appear.

**Comment by prashnts** [comment]
Is this bug still there? I think it's fixed by https://github.com/CyberCRI/iLearn/commit/f14a3aff6794e529b18faf746413a047cf88ce33
and https://github.com/CyberCRI/iLearn/commit/cf3db0aa8de4a2766f93d46b435c73c49d57df9d

**Comment by iryna1** [comment]
Indeed. Fixed.
