### ISSUE TITLE
[Map] Be able to send the link of my map to others

### ISSUE THREAD

**Issue by iryna1** [CyberCRI/learn-ext#95]
##User Story: 
Once the user has entered interesting resources on a map and wants to share them with others, the user should be able to share a link with the finished work with others. 

- [x] Therefore we need to have a sharable map+ressources accessible via a link.

NB: In the future we would like to allow users to include only a part of resources. This should either be based on privacy setting or on a result of a search (based on a personnal tag, a concept, a category...). What we develop here should be compatible with this future objective.

- [x] Rights: the user who consults should not be able to modify anything (and no settings).

**Comment by prashnts** [comment]
We has a quick call to clarify this, and the way to go is:

- [ ] Make "discover" tab store state of selected concepts in map to display it
- [ ] Auth: if user is not logged in, don't show "my resources", "my group" buttons;
- [ ] Url will update automatically to include the <user id> and <x, y> coords of wherever you've clicked

_(i'll expand this comment later)_
